# Generated by Django 2.2.9 on 2020-01-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='toys',
            field=models.ManyToManyField(to='pets.Toy'),
        ),
    ]
